# .github/workflows/kicad-diff.yml
name: KiCad visual diff
on:
  push:
    paths: ["PCB/**/*.kicad_pcb", "PCB/**/*.kicad_sch"]
  pull_request:
    paths: ["PCB/**/*.kicad_pcb", "PCB/**/*.kicad_sch"]
permissions:
  contents: read
  pull-requests: write
jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with: { fetch-depth: 0 }
      - uses: sksat/kicadiff@v0.2.0
        with:
          path: PCB
          upload-artifact: 'true'
          pr-comment: 'true'
          pr-description: 'true'